### ISSUE TITLE
row.names = NULL action

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#1]
Hey Michael, @lawremi
I saw that `DataFrame(score = c(A = 1, B = 2), row.names = NULL)` is returning a DataFrame with rownames taken from the named vector. 
Is this a bug as it should follow the `data.frame` behavior? 
Regards,
Marcel

**Comment by hpages** [comment]
Hi Michael,
Please don't forget to push your changes to git.bioconductor.org. Thanks!
H.

**Comment by lawremi** [comment]
Sure, I didn't forget. Just waiting a day or so for the fix to be confirmed. Not sure what the best practice should be.

**Comment by hpages** [comment]
Best/easiest way to have the fix confirmed is probably to send it to the build system so personally I prefer to make changes to git.bioconductor.org first. Then when I remember I resync the Github repo (just did it yesterday for S4Vectors and today for IRanges and GenomicRanges). I'm not worried about the packages on GitHub temporarily lagging a little bit behind the packages on git.bioconductor.org. Maybe I'll come up with a script that runs automatically every day to resync some of the packages on GitHub with git.bioconductor.org.

I'm sure many developers will prefer to do it the other way around though...

**Comment by lawremi** [comment]
Yes, it seems like both will need to happen simultaneously, because we want to promptly respond to GitHub issues, while also using the continuous integration.

**Comment by mtmorgan** [comment]
Nitesh [suggests](https://stat.ethz.ch/pipermail/bioc-devel/2017-September/011451.html) some git configuration magic to push to both with one command.

**Comment by lawremi** [comment]
Thanks for that. I think I'll adopt that practice.
