### ISSUE TITLE
Error: duplicate row.names

### ISSUE THREAD

**Issue by hchetia** [Bioconductor/S4Vectors#101]
Hi,
I am trying to annotate CpG calls ( a methylkit object). 
**meth_gr** has CpG calls coerced into GRanges.
**gene_bodies_hg38** has the gene body information extracted from a TXDB object made with Gencode 39 GTF.

I have used the **findOverlaps** function to find the matches between **"gene_bodies_hg38" and "meth_gr"** and coerce them into a data frame.
My code is provided sequentially below with the messages as image.

`matches <- findOverlaps(meth_gr,gene_bodies_hg38)​`
`meth_gr[matches@from]`
​
<img width="947" alt="image" src="https://user-images.githubusercontent.com/64626735/159536041-9c621df9-03b9-49aa-86e6-54c882ec05c0.png">

`gene_bodies_hg38[matches@to]`
<img width="603" alt="image" src="https://user-images.githubusercontent.com/64626735/159536117-a3e9a613-aeea-4023-9c42-a6ee442082ab.png">

`mcols(meth_gr) <- as.data.frame(gene_bodies_hg38[matches@to])`
<img width="979" alt="image" src="https://user-images.githubusercontent.com/64626735/159536209-930d893f-c7cb-4874-8b9a-7e9fa28d1f75.png">

How can I resolve this error?

Best,
Hasna

**Comment by DarioS** [comment]
I would expect it to work. The default value of `row.names` is `NULL`.

```r
as.data.frame(x, row.names = NULL, optional = FALSE, ...)
```

Which version of GenomicRanges are you using? It looks like it should work correctly in the latest one.

```r
        if (!is.null(names(x)))
            names(x) <- NULL
```

However, I tested it with the newest, but it didn't. Hmm. Also, there is some code which would never get executed.

```r
    function(x, row.names=NULL, optional=FALSE, ...)
    {
        if (missing(row.names)) # Impossible. Perhaps written before parameter had a default.
            row.names <- names(x)
```

Also, you should use accessors. So, `to(matches)` and not `matches@to`.

It's also good to make a minimal example, such as:

```r
gr <- GRanges(Rle(c("chr2", "chr2", "chr1", "chr3"), c(1, 3, 2, 4)), IRanges(1:10, width=10:1))
names(gr) <- rep('G', 10)
as.data.frame(gr) # Triggers the error.
```

**Comment by LiNk-NY** [comment]
The `as.data.frame` method has:
```r
        if (missing(row.names))
            row.names <- names(x)
```
It's not impossible, it's missing by default when not specified...
so you'd have to do : 
```r
> as.data.frame(gr, row.names = NULL)
   seqnames start end width strand
1      chr2     1  10    10      *
2      chr2     2  10     9      *
3      chr2     3  10     8      *
4      chr2     4  10     7      *
5      chr1     5  10     6      *
6      chr1     6  10     5      *
7      chr3     7  10     4      *
8      chr3     8  10     3      *
9      chr3     9  10     2      *
10     chr3    10  10     1      *
```
to avoid the duplicated row names.

**Comment by hpages** [comment]
@hchetia There are several things wrong with

    mcols(meth_gr) <- as.data.frame(gene_bodies_hg38[matches@to])

First you should not try to turn the right GRanges into an ordinary data.frame because the metadata columns you're putting on `meth_gr` (or on any Vector derivative) should be represented as a DataFrame.

Second, you should never access the slots of an S4 object directly. Always use an accessor function instead:

    x <- GRanges(c(A="chr1:10-20", B="chr1:55-70"))
    y <- GRanges(c(a="chr1:50-60", b="chr1:1-10", c="chr1:1-100"))

    hits <- findOverlaps(x, y)
    hits
    # Hits object with 4 hits and 0 metadata columns:
    #       queryHits subjectHits
    #       <integer>   <integer>
    #   [1]         1           2
    #   [2]         1           3
    #   [3]         2           1
    #   [4]         2           3
    #   -------
    #   queryLength: 2 / subjectLength: 3
    
    queryHits(hits)   # instead of hits@from
    # [1] 1 1 2 2
    
    subjectHits(hits)  # instead of hits@to
    # [1] 2 3 1 3

Third, and more importantly, I don't see any reason a priori why `meth_gr` and `gene_bodies_hg38[matches@to]` would have the same length so it doesn't make sense to try to set the latter as the metadata columns of the former, and it won't work. With my little example above:

    y[subjectHits(hits)]
    # GRanges object with 4 ranges and 0 metadata columns:
    #     seqnames    ranges strand
    #        <Rle> <IRanges>  <Rle>
    #   b     chr1      1-10      *
    #   c     chr1     1-100      *
    #   a     chr1     50-60      *
    #   c     chr1     1-100      *
    #   -------
    #   seqinfo: 1 sequence from an unspecified genome; no seqlengths
    
    mcols(x) <- DataFrame(Y=y[subjectHits(hits)])
    # Error in normarg_mcols(value, class(x), length(x)) : 
    #   trying to set a metadata column of length 4 on an object of length 2

Not sure why you would try to do something like this.

If you need more help with this, it's better to ask on our [support site](https://support.bioconductor.org). GitHub issues are primarily for bug reports.

Thanks,
H.
