### ISSUE TITLE
  'class2' must be the name of a class or a class definition

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#105]
Hi Hervé, @hpages 
It looks like the coercion method is broken in Bioc-devel:

```r
library(SummarizedExperiment)
library(S4Vectors)
assayList <- list(A = matrix(1:4, nrow = 2), B = SummarizedExperiment())
as(assayList, "SimpleList")
#' Error in extends(cl, ans) : 
#'  'class2' must be the name of a class or a class definition
packageVersion("S4Vectors")
#' [1] '0.33.16'
```

**Comment by hpages** [comment]
ouch, that seems to break a few packages! **cydar**, **FindIT2**, **midasHLA**, **missRows**, **MuData**, **MultiAssayExperiment**, **netDx**, **SingleR**, and **TimiRGeN** :sweat_smile: 

Should be fixed in **S4Vectors** 0.33.17 (see 9f1d9279fdd5965f32d52e5945515ed03574bfd7).

Thanks Marcel!

H.
