### ISSUE TITLE
Could I get old version S4Vectors?

### ISSUE THREAD

**Issue by ChoiJi-Hye** [Bioconductor/S4Vectors#106]
Hi.
I want to use a old package, It doesn't work current R version.
It is used in 3.2 version R and it requires >=0.9.42 version but under 0.10.3 S4Vectors.
However, Bioconductor offers 0.8.11 or 0.10.3 version. I couldn't find version I want.

I want to get 0.9.42 version, or a similar version.
Could I get older S4Vectors version package?

Thanks for your help.

**Comment by vjcitn** [comment]
Just for clarity, I wanted to mention that a) I built R 3.2 from source, b) I used
```
source("https://bioconductor.org/biocLite.R")
```
to get the installation tool, as BiocManager was not available for R 3.2, and c)
```
biocLite("S4Vectors")
```
gave me S4Vectors 0.8.11.  It seems you got that far already?  That's the version we
know is suitable for R 3.2, from 2015.  I will now examine how one might get an 0.9 version 
of S4Vectors.  Note that when y is odd in x.y.z the package version is being defined in
the "devel" branch for Bioconductor.  I am not sure we have a way to provide this without
ad hoc manual intervention.

**Comment by vjcitn** [comment]
I don't see a way right now; others may have more insight.  Are you sure you cannot use the 0.10 version in R 3.3 to accomplish what you want to accomplish?  I think it would match the functionality (possibly exceeding it) of the 0.9 version.

**Comment by lshep** [comment]
I don't think there is a way for in-between versions for older versions of Bioconductor. We introduced an Archive starting in Bioconductor 3.6 that would have various versions of the package besides the last stable release.  Also as @vjcitn mentioned the odd y indicated it was a devel version which we do not keep.  The closest version to the one you want is actually the stable version of 0.10.3 (in Bioc 3.3)

**Comment by vjcitn** [comment]
@ChoiJi-Hye since this is not really an issue for the S4Vectors package in github, I'd like to close it and propose that you post a query about your specific need to support.bioconductor.org.  There may be someone out there who is using the legacy versions of interest to you and who can provide more help.

**Comment by ChoiJi-Hye** [comment]
@lshep, @vjcitn, Thanks you for your reply.
Unfortunately, Where I work , I can use Internet for security.
Therefore, I can't use biocLite, and there is a trouble with gcc in R 3.3 version so I look for suitable version of dependencies.

Thank you for your help.

**Comment by mtmorgan** [comment]
One can search for the 'version bump' in git
```
$ git clone https://git.bioconductor.org/packages/S4Vectors; cd S4Vectors
$ git log -S 0.9.42 --oneline
46fd46a explicitly promote rowSums/colSums/rowMeans/colMeans to S4 generics
45ffd8e rename internal helper class WindowNSBS -> RangeNSBS (not exported)
```
These are actually sequential commits, 45ffd8e goes to version 0.9.42, and the second to 0.9.43
```
46fd46a explicitly promote rowSums/colSums/rowMeans/colMeans to S4 generics
45ffd8e rename internal helper class WindowNSBS -> RangeNSBS (not exported)
760c571 minor cosmetic
```
so S4Vectors version 0.9.42 could be installed from this commit
```
git checkout 45ffd8e
R CMD build .  # produces a tar.gz to be installed on your cluster
```
Unfortunately, one would like to also install contemporary dependencies. This could be accomplished through similar processes, but would be tedious and imperfect.
