### ISSUE TITLE
Improve and expand the Factor-class with raw index and more subclasses

### ISSUE THREAD

**Issue by MalteThodberg** [Bioconductor/S4Vectors#107]
I’m a big fan of the Rle-class, but I’ve encountered a common use-case where Rle-compression is ineffecient: Storing a large number of a few non-repeating values, e.g. allele information (Ref/Alt) from a GWAS or VEP prediction for SNPs.

Here’s and example:

```
# Storing a million DNA bases
> dna_char <- sample(DNA_BASES, size=1e6, replace=TRUE)
> 
> # Current bioconductor options
> dna_rle <- Rle(dna_char)
> dna_dss <- DNAStringSet(dna_char)
> dna_fac <- factor(dna_char)
> 
> # Sizes
> lobstr::obj_size(dna_char)
8,000,272 B
> lobstr::obj_size(dna_rle)
9,000,952 B
> lobstr::obj_size(dna_dss)
15,323,368 B
> lobstr::obj_size(dna_fac)
4,000,688 B
```

Neither Rle compression (or DNAStringSet) is as efficient as a simple factor. However, even the factor class is inefficient, as it stores the index as whole integers. The smallfactor package (https://github.com/coolbutuseless/smallfactor) has the interesting idea of storing the factor index as raw instead:

```
> # smallfactor storing index as raw
> dna_byte <- bytefactor(dna_char)
> lobstr::obj_size(dna_byte)
1,000,696 B
```

Which is only 25% compared to using factor and 12% compared to using Rle - an excellent improvement.

smallfactor has only a barebone implementation that is based on S3 however. Since S4Vectors already includes the Factor-class I thought it might be fairly easy to upgrade the S4 class, by simply allowing the @index slot of Factor to be the class union of integer and raw:

```
setClass("Factor",
         contains="Vector",
         representation(
             levels="vector_OR_Vector",
             index="integer_or_raw"
         )
)

```
And then the constructor would just have to take note of the length of the @levels slot when constructing the object: If there are less than 256 unique values, index is stored as raw instead of integer.

I think a similar idea is used in RleMatrix from DelayedArray and bigstatsr (https://privefl.github.io/bigstatsr/reference/FBM.code256-class.html)

(A small sidenote: smallfactor also includes an even more compressed index with bitfactor by compressing multiple value in a single integer, but I’m not sure how efficient that is in term of computation time and how difficult it would be to implement...)

Another excellent addition would be to include specific subclasses for each type of levels a Factor has, eg.  

```
setClass("CharacterFactor",
         contains="Factor",
         slots=c(levels="character"))
```

Similar to the different subclasses of Lists (e.g. SimpleList vs IntegerList, CharacterList, etc) this would allow efficient shortcuts by directly operating on levels, like max() for an IntegerFactor and toupper() for a CharacterFactor. The other core packages could expand this like GenomicRanges has with GRangesFactor, e.g. DNAStringSetFactor.

Together these changes would make the Factor-class much, much better than the base S3 factor!

**Comment by hpages** [comment]
Lots of good ideas here, thanks.

For your original example, I'm surprised that you didn't try to use a simple DNAString object. This would be much more efficient than any of the other things you tried:
```
dna_dnastr <- DNAString(paste(dna_char, collapse=""))
object.size(dna_dnastr)
# 1002200 bytes
```
The DNAString representation uses 1 byte per letter plus a small overhead:
```
object.size(new("DNAString"))
# 2200 bytes
```
so memory footprint reported by `object.size()` for `dna_dnastr` is as expected.

BTW I'm not really sure I trust `lobstr::obj_size()` in this case that's why I'm using `object.size()`. For example:
```
lobstr::obj_size(new("DNAString"))
# 2.63 MB   <--- fishy!!
```
This seems to stem from `lobstr::obj_size()` strange behavior on empty environments:
```
lobstr::obj_size(new("environment"))
# 1.09 MB
```
Anyways, I just made a small change in **Biostrings**/**XVector** to work around this. With this change `object.size()` and `lobstr::obj_size()` mostly agree on the size of DNAString objects.

**Comment by MalteThodberg** [comment]
Yes you are right, sizes reported by `lobstr::object_size` and `pryr::object_size` are quite different! `pryr::compare_size` shows it also. `DNAStringSet` becomes more competitive when using `base::object.size()`

You are absolutely right that using a `DNAString` is efficient as well in the simplest case of only SNPs. However, if indels are included a `DNAStringSet` is the only option as far as I'm aware?

After experimentation with some real datasets it seems that an overall good approach for storing Ref/Alt alleles is to use a `Factor` with `DNAStringSet` levels:

```
> object.size(x) # 19430465 Alt alleles as a factor
233205208 bytes
> object.size(DNAStringSet(x))
271625984 bytes
> object.size(Factor(DNAStringSet(x)))
138061672 bytes
```

**Comment by hpages** [comment]
With the changes I made to **Biostrings**/**XVector** 2 days ago (**Biostrings** 2.65.3 / **XVector** 0.37.1), `utils::object.size()`, `lobstr::obj_size()`, and `pryr::object_size()` finally agree.

If you're also dealing with non-snv SNPs, a Factor with DNAStringSet levels indeed seems optimal. Makes a lot of sense.

Note that if `x` is already an ordinary factor, you can construct the Factor object very cheaply with `Factor(levels=DNAStringSet(levels(x)), index=as.integer(x))`. This avoids the cost of having the `Factor()` constructor compute the levels and match the input values to them:
```
library(Biostrings)
levels <- c(DNA_BASES, "", "AAA", "AAC", "ACG", "AT", "ATA", "ATT", "CA", "CC", "CCG", "CGGT", "CT", "CTT", "TA", "TAA", "TAC", "TG", "TT", "TTT", "TTTAT")
x <- factor(sample(levels, 20e6, replace=TRUE), levels=levels)

system.time(Factor(DNAStringSet(x)))
#    user  system elapsed 
#   2.260   0.476   2.736

system.time(Factor(DNAStringSet(x), levels=DNAStringSet(levels(x))))
#    user  system elapsed 
#   1.348   0.284   1.631

system.time(Factor(levels=DNAStringSet(levels(x)), index=as.integer(x)))
#    user  system elapsed 
#  0.058   0.036   0.095
```
Anyways, seems like you have a solid use case for using a `raw` index. I'll work on this.

**Comment by hpages** [comment]
Done in **S4Vectors** 0.35.2 (see commit 0e4a8bf63719c8b7524ef1d5151900e7e84677a4). With this new version of **S4Vectors**:
```
library(Biostrings)
levels <- c(DNA_BASES, "", "AAA", "AAC", "ACG", "AT", "ATA", "ATT", "CA", "CC", "CCG", "CGGT", "CT", "CTT", "TA", "TAA", "TAC", "TG", "TT", "TTT", "TTTAT")
x <- factor(sample(levels, 20e6, replace=TRUE), levels=levels)
dna_f <- Factor(levels=DNAStringSet(levels(x)), index=as.raw(x))
object.size(dna_f)
# 20005592 bytes
```

As for your other suggestion to define specialized Factor subclasses like IntegerFactor, CharacterFactor etc... I'm not convinced that defining `max()` for IntegerFactor and `toupper()` for CharacterFactor would add significant value vs simply defining these methods for the Factor class. We also need to consider the "cost" of maintaining/documenting a myriad of Factor subclasses. Anyways, this is a separate discussion. Please open a new issue if you want to pursue this. Thanks!

**Comment by MalteThodberg** [comment]
Super cool (and very quick) - I will give a spin!

Might it make sense to give the Factor-class a droplevels method, where it demotes the index to raw if there are few enough levels?

**Comment by hpages** [comment]
Sure. Done in **S4Vectors** 0.35.3.

**Comment by hpages** [comment]
Let's close this.
