### ISSUE TITLE
DataFrame assignment forces names of other columns to be unique

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#108]
I can construct a `DataFrame` with duplicated names:

```r
library(S4Vectors)
y <- DataFrame(x=1, x=2, aa=2, check.names=FALSE)
y
## DataFrame with 1 row and 3 columns
##           x         x        aa
##   <numeric> <numeric> <numeric>
## 1         1         2         2
```

However, any type of assignment seems to run `make.unique()` on the column names:

```r
y[["aa"]] <- 3
y
## DataFrame with 1 row and 3 columns
##           x       x.1        aa
##   <numeric> <numeric> <numeric>
## 1         1         2         3
```

This is quite surprising, given that my assignment doesn't touch any of the `x` columns. I would have expected that the assignment would just leave them alone and allow me to decide what to do with duplicate names. The presence of such duplicates is not uncommon when dealing with/cleaning up `cbind`ed objects, especially deeply nested ones, e.g., in SEs.

<details>
<summary>Session information</summary>

```
R version 4.2.0 Patched (2022-06-02 r82447)
Platform: x86_64-apple-darwin19.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Users/luna/Software/R/R-4-2-branch/lib/libRblas.dylib
LAPACK: /Users/luna/Software/R/R-4-2-branch/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] S4Vectors_0.35.0    BiocGenerics_0.43.0

loaded via a namespace (and not attached):
[1] compiler_4.2.0
```
</details>

**Comment by hpages** [comment]
Yeah, and we also observe this for other forms of subsetting:
```
DF <- DataFrame(x=1, x=2, aa=2, check.names=FALSE)

DF[ , 1:2]
# DataFrame with 1 row and 2 columns
#           x       x.1
#   <numeric> <numeric>
# 1         1         2

DF[1:2]
# DataFrame with 1 row and 2 columns
#           x       x.1
#   <numeric> <numeric>
# 1         1         2
```

The subsetting methods for DataFrame have historically tried to maintain uniqueness of the colnames by having calls to `make.unique()` in various strategic places like [here](https://github.com/Bioconductor/S4Vectors/blob/8759d88507f9979a0ddba7335fcbe3a1449607c2/R/DataFrame-class.R#L512), [here](https://github.com/Bioconductor/S4Vectors/blob/8759d88507f9979a0ddba7335fcbe3a1449607c2/R/DataFrame-class.R#L632), or [here](https://github.com/Bioconductor/S4Vectors/blob/8759d88507f9979a0ddba7335fcbe3a1449607c2/R/DataFrame-class.R#L746), probably in an effort to mimic what happens with ordinary data.frames:
```
df <- data.frame(x=1, x=2, aa=2, check.names=FALSE)

df[ , 1:2]
#   x x.1
# 1 1   2

df[1:2]
#   x x.1
# 1 1   2
```

Even though, for your original example above (`[[<-`), it seems that data.frames actually do the right thing:
```
df[["aa"]] <- 3
df
#   x x aa
# 1 1 2  3
```
I never liked this and I'm all for getting rid of it. The only place where it's probably ok to keep this feature is in the `DataFrame()` constructor where `check.names` is TRUE by default.

If nobody objects (@lawremi ?), I will make this change. IIRC some unit tests explicitly expect the current behavior so might need to be adjusted.

H.

**Comment by hpages** [comment]
Done in **S4Vectors**  0.35.1 (see commit 11a5be380857f7697e185c41c9d9a1913a0d5c5a).
