### ISSUE TITLE
AEbufs.c: warning: conversion from 'long long unsigned int' to 'size_t' {aka 'long unsigned int'} changes value from '4294967296' to '0' [-Woverflow]

### ISSUE THREAD

**Issue by barracuda156** [Bioconductor/S4Vectors#112]
Can this be fixed? (This looks like a 32-bit issue.)
```
/opt/local/bin/gcc-mp-12 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isystem/opt/local/include/LegacySupport -I/opt/local/include   -fPIC  -pipe -Os -arch ppc  -c AEbufs.c -o AEbufs.o
AEbufs.c: In function '_increase_buflength':
AEbufs.c:16:23: warning: conversion from 'long long unsigned int' to 'size_t' {aka 'long unsigned int'} changes value from '4294967296' to '0' [-Woverflow]
   16 | #define MAX_BUFLENGTH (128ULL * MAX_BUFLENGTH_INC)  // 2^32
      |                       ^
AEbufs.c:31:16: note: in expansion of macro 'MAX_BUFLENGTH'
   31 |         return MAX_BUFLENGTH;
      |                ^~~~~~~~~~~~~
```

**Comment by hpages** [comment]
Thanks for the report. This should be adressed in **S4Vectors** 0.37.6. See commit 3b83d5fa6f536715119dfb36bd2ea0435d8b6990.

**Comment by barracuda156** [comment]
> Thanks for the report. This should be adressed in **S4Vectors** 0.37.6. See commit [3b83d5f](https://github.com/Bioconductor/S4Vectors/commit/3b83d5fa6f536715119dfb36bd2ea0435d8b6990).

Thank you! I will update `S4Vectors` to current Github version then. Bioconductor one is stuck at 0.36.2.

**Comment by hpages** [comment]
Sounds good but note that **S4Vectors** 0.37.6 is the development version of the package and it belongs to BioC 3.17 which is still in development. BioC 3.17 will be released at the end on the month and is only guranteed to work with R 4.3 (the development version of R).

**Comment by barracuda156** [comment]
> Sounds good but note that **S4Vectors** 0.37.6 is the development version of the package and it belongs to BioC 3.17 which is still in development. BioC 3.17 will be released at the end on the month and is only guranteed to work with R 4.3 (the development version of R).

Got it, thank you for the clarification. I will run tests prior to updating then. Macports has `R` 4.2.3 at the moment.

**Comment by hpages** [comment]
Oops, my earlier commit did not really eliminate the risk of a long unsigned int overflow, sorry. Hopefully my last commit (3021a0c8afeb01a0aeb351b680ca9af5a8d84b3e) does that. Make sure to install/test that instead. Thanks!
