### ISSUE TITLE
S4Vectors

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#114]

**Comment by LiNk-NY** [comment]
> replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘AnnotationDbi’

https://support.bioconductor.org/p/9151164/

**Comment by hpages** [comment]
This warning is actually originating from an import conflict in **AnnotationDbi**, which I fixed yesterday: https://github.com/Bioconductor/AnnotationDbi/commit/ccc9f424fa361e2e2378ba4d407763c32fc10642
