### ISSUE TITLE
Build from a clone version

### ISSUE THREAD

**Issue by Richardzhang2009** [Bioconductor/S4Vectors#120]
Dear author,

When I am trying to build the package from the downloaded S4Vectors github repo, I run the following code:

devtools::build("/path-to-S4Vectors/")

Then there are errors:

1. Error: processing vignette 'S4QuickOverview.Rnw' failed with diagnostics:
    chunk 1 (label = setup) 

2. Error in library(IRanges) : there is no package called ‘IRanges’

For the first error, I have no clue how to fix that. And for the second error, it confuses me that my original goal is to install IRanges and the S4Vectors are supposed to be the depend.

My session_info is:

version  R version 4.3.2 (2023-10-31)
os           macOS Sonoma 14.2.1
system   aarch64, darwin20
rstudio  2023.12.0+369 Ocean Storm (desktop)

Thanks,

Han

**Comment by LiNk-NY** [comment]
Hi Han, @Richardzhang2009 

I could not reproduce this with `S4Vectors` version `0.41.3`. 

We recommend that you use `R CMD` `INSTALL` / `build` and `check` from the command line instead. We cannot guarantee success with external tools, e.g., `devtools`. Make sure that you have installed all of the `S4Vectors` dependencies using `BiocManager::install("S4Vectors")`. 

Best, 
Marcel

**Comment by hpages** [comment]
Why are you trying to install **IRanges** from GitHub? **IRanges** is a Bioconductor package and Bioconductor packages should always be installed with `BiocManager::install()`. See https://bioconductor.org/packages/IRanges.

> And for the second error, it confuses me that my original goal is to install IRanges and the S4Vectors are supposed to be the depend.

`devtools::build("path/to/S4Vectors")` (or `R CMD build path/to/S4Vectors`) tries to build the vignette included in **S4Vectors** and this vignette makes use of the **IRanges** package. Note that this is why **IRanges** is listed in the `Suggests` field of **S4Vectors**. The suggested packages are usually needed to build a package source tarball. 

To work around this chicken-egg situation, you can build **S4Vectors** with `R CMD build --no-build-vignettes path/to/S4Vectors`. Then install the resulting tarball with `R CMD INSTALL`.

But again, installing Bioconductor packages directly from GitHub is strongly discouraged. Even if you somehow manage to do it,  you will most likely end up with a broken installation.

**Comment by hpages** [comment]
@Richardzhang2009 Have you made any progress on this?

**Comment by hpages** [comment]
no news == good news I suppose
