### ISSUE TITLE
Expose make.names to as.data.frame generic for signature DataFrame

### ISSUE THREAD

**Issue by doliv071** [Bioconductor/S4Vectors#121]
I am building a package for bioconductor that works with SingleCellExperiment objects and I have come across an issue with the conversion from DataFrame to data.frame. Specifically, because column names of a matrix can be duplicated, the row names of colData which are stored as a DataFrame can also be duplicated. Currently, the conversion to data.frame via the as.data.frame method always produces valid row names via make.unique.

My issue (really an enhancement request) is that I would like this type of situation to throw an error if I supply `make.names = FALSE` to `as.data.frame`, unfortunately all `...` are ignored by the current version of the method. As I'm aware that handling some but not all `...` arguments would cause confusion, I would like to request that make.names be exposed as a named argument which would match the base S3 method for class 'matrix'.

Example:
```
> (DF <- DataFrame(A = 1:3, row.names = c("a", "b", "b")))
DataFrame with 3 rows and 1 column
          A
  <integer>
a         1
b         2
b         3

> as.data.frame(DF)
    A
a   1
b   2
b.1 3

# this should error
> as.data.frame(DF, make.names = F)
    A
a   1
b   2
b.1 3
Warning message:
In .local(x, row.names, optional, ...) : Arguments in '...' ignored
```

session info:
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] S4Vectors_0.36.2    BiocGenerics_0.44.0

loaded via a namespace (and not attached):
[1] compiler_4.2.1    tools_4.2.1       rstudioapi_0.15.0
```

**Comment by hpages** [comment]
Sorry for the delay. `make.names` argument added to **S4Vectors** 0.41.5 (see commit b9904ce4a9c96ad14f6040167c9f03b7914ece8a):
```
DF <- DataFrame(A=11:13, row.names=c("a", "b", "a"))

as.data.frame(DF)
#      A
# a   11
# b   12
# a.1 13

as.data.frame(DF, make.names=FALSE)
# Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
#   duplicate row.names: a
```
Cheers,
H.
