### ISSUE TITLE
Getting deprecation warning from `as.data.frame` on BioC devel

### ISSUE THREAD

**Issue by danielinteractive** [Bioconductor/S4Vectors#122]
Hello,

in downstream R package `hermes` we get a deprecation warning that seems to be able to be fixed in `S4Vectors`. I collected a bit more information in https://github.com/insightsengineering/hermes/issues/227 description.
Is this a known issue that you are working on already maybe?

Thanks,
cheers
Daniel

**Comment by LiNk-NY** [comment]
Hi @danielinteractive 
This is an issue in R and has been reported here: 
https://stat.ethz.ch/pipermail/r-devel/2024-March/083265.html

**Comment by hpages** [comment]
Supposedly addressed in R-devel svn rev 86139 so the deprecation warning you get in **hermes** should go away with the latest R devel. Can you confirm @danielinteractive?

**Comment by danielinteractive** [comment]
Thanks a lot @hpages !

For confirming a quick question - previously I was using the docker image bioconductor/bioconductor_docker:devel (https://hub.docker.com/layers/bioconductor/bioconductor_docker/devel/images/sha256-b7ebf92e469e7c1d424b5bc28dda30ec354beb380a0bfd169e5b55dfeb16b35a?context=explore) for this purpose. However it hasn't been updated in the last few days. Maybe I just need to wait a few more days? Or is there another trick maybe?

**Comment by hpages** [comment]
Yes, bioconductor/bioconductor_docker:devel should be updated soon. @almahmoud?

**Comment by hpages** [comment]
BTW @danielinteractive, after running `docker pull bioconductor/bioconductor_docker:devel` on my laptop and starting the container, I get `R Under development (unstable) (2024-03-20 r86162)`:

![image](https://github.com/Bioconductor/S4Vectors/assets/8810451/5701e1ac-d0c4-42f0-a9c0-6a09b8057d79)

So it seems that the image did get updated.

Cheers,
H.

**Comment by danielinteractive** [comment]
Thanks @hpages , indeed! Downloading now.

**Comment by danielinteractive** [comment]
I can confirm that this is fixed now.
