### ISSUE TITLE
DataFrame constructors and stringsAsFactors

### ISSUE THREAD

**Issue by wolfganghuber** [Bioconductor/S4Vectors#13]
The documentation says " On the whole, the ‘DataFrame’ behaves very similarly to ‘data.frame’, in terms of construction, subsetting, splitting, combining, etc." but I understand that 'stringsAsFactors' arguments are expanded as data columns. For easier exchangeability with regular 'data.frame' and reducing programmers' mental load, why not have the constructors accept the 'stringsAsFactors' argument, complain if its not TRUE, and then swallow it?

**Comment by lawremi** [comment]
`DataFrame()` doesn't actually ensure one behavior or the other, as it all depends on the coercion of each argument to DataFrame. Thus, I made it so that `DataFrame()` ignores `stringsAsFactors` and warns if it is non-missing. Thanks for the suggestion.
