### ISSUE TITLE
Subsetting errors with Vector

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#14]
Apologies if you're already aware of this, but a recent change in Vector assignment seems to have broken a large number of packages on the BioC-devel build system. This is most easily demonstrated with:

```r
library(IRanges)
library(S4Vectors)
aa <- CharacterList("a", paste0("d", 1:2), paste0("b", 1:3), c(), "c")
bb <- CharacterList(paste0("sna", 1:2),"foo", paste0("bar", 1:3),c(),"hica")
df <- DataFrame(aa=aa, bb=bb, cc=11:15)
res1 <- expand(df, colnames="aa", keepEmptyRows=TRUE)
```

... which spits out the now-ubiquitous error:

```
Error: subscript is a NSBS object that is incompatible with the current
  subsetting operation
```

Progressively re-installing _S4Vectors_ across its recent Git history and testing the above code suggests that the problem was introduced at 38cfe9256da9d6a185a22b5e08dbc2a0ebe0ceeb. Some `debug`ging of `normalizeSingleBracketSubscript` further indicates that the first call to `NSBS` has `allow.append` set to `TRUE`, but the subsequent call instead has `allow.append` set to `FALSE`. Forcing `allow.append <- TRUE` seems to avoid the error.

**Comment by lawremi** [comment]
Sorry, I reverted the problematic commit.
