### ISSUE TITLE
Nested DataFrames breaks as.data.frame,DataFrame-method

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#16]
Calling:

```r
A <- DataFrame(1:5)
B <- DataFrame(2:6)
B$A <- A
as.data.frame(B)
```

gives:

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 5, 1
```

Admittedly it's not clear what `as.data.frame` should do in this instance - I would have hoped for it to "promote" the fields in the nested `DataFrame` to create a `data.frame` containing all fields at the same  level, but this could get pretty messy with potential name clashes. However, if an error is the intended outcome, then perhaps a more informative error message would be in order - the current message gives no indication that the problem is that of a nested S4 object as one of the fields.

```
R version 3.5.0 Patched (2018-04-30 r74679)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/R-3-5-branch/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/R-3-5-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] S4Vectors_0.19.9    BiocGenerics_0.27.0

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0   
```

**Comment by lawremi** [comment]
Should I work on this or is @hpages already on it? We should probably start making use of the issue assignment feature.

**Comment by hpages** [comment]
I'm looking into this. I'm currently refactoring `as.data.frame,DataFrame` to use `as.data.frame()` instead of `as.list()` on each column. I'll commit something soon.

**Comment by hpages** [comment]
Should be fixed in d84bc18dea7a232061946fbfe30d2072b88705a7

Thanks @LTLA for the catch!

H.

**Comment by hpages** [comment]
Also I might port this to release but I'll wait a couple of days before doing that.

**Comment by LTLA** [comment]
Thanks Herve, looks like it's working.

**Comment by lawremi** [comment]
Thanks @hpages !
