### ISSUE TITLE
is this behaviour expected?

### ISSUE THREAD

**Issue by sa-lee** [Bioconductor/S4Vectors#18]
I think this is to do with the recent changes to names/rownames in `DataFrame`:

``` r
library(S4Vectors)
nm <- List(a = c(1, 3), b = 5)
# propagates names in list to rownames in DataFrame
mcols(nm) <- DataFrame(stuff = c("a", "b"))
mcols(nm)
#> DataFrame with 2 rows and 1 column
#>         stuff
#>   <character>
#> a           a
#> b           b
# attempt to delete rownmaes
rownames(mcols(nm)) <- NULL
# the row names are still there
mcols(nm)
#> DataFrame with 2 rows and 1 column
#>         stuff
#>   <character>
#> a           a
#> b           b
```

**Comment by hpages** [comment]
This is expected and is not new: `rownames(mcols(x)) <- new_rownames` never had any effect on the rownames of the DataFrame returned by `mcols(x, use.names=TRUE)`.

What's important to keep in mind is that `mcols(x, use.names=TRUE)` propagates **`names(x)`** so the returned rownames won't change unless you modify the names on `x`. What has changed recently (in S4Vectors 0.19.11, see 04cc9516af986b30445e99fd1337f13321b7b4f6) is that `use.names` now is TRUE by default (used to be FALSE).

**Comment by sa-lee** [comment]
Ok makes sense to me. Thanks for the response!
