### ISSUE TITLE
Row Subsetting Performance for a Large DataFrame

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/S4Vectors#21]
Is there a performance optimisation which could be made to the row subsetting for a large DataFrame (such as might typically be created by the `wideFormat` function of MultiAssayExperiment)? It's about 30 times slower than for a data.frame of the same dimensions.

```r
bigTable <- matrix(rpois(50 * 100000, 100), ncol = 100000)
library(S4Vectors)
bigDataFrame <- DataFrame(bigTable)
trainingSamples <- 1:45
> system.time(bigDataFrame[trainingSamples, ])
   user  system elapsed 
 43.008   0.315  43.344 
bigdata.frame <- data.frame(bigTable)
> system.time(bigdata.frame[trainingSamples, ])
   user  system elapsed 
  1.533   0.004   1.538
```

Coercing to a basic data frame gains some time saving but not much.

```r
> system.time(basicTable <- as(bigDataFrame, "data.frame"))
   user  system elapsed 
 18.042   0.183  18.228
```

**Comment by lawremi** [comment]
The speed up brings it from about 40X slower to about 14X slower on my laptop. The basic problem is of course dispatch. It looks like the methods package is doing the `loadMethod()` thing again on every dispatch, which is a bug that just keeps cropping up. It would be nice to avoid dispatch on `NSBS()` for every column since we form an NSBS at the DataFrame level. I realize it's doing some sanity checking but it's a big price to pay in this case. @hpages could comment on that.

**Comment by lawremi** [comment]
Turns out that the call to `methods:::loadMethod()` was caused by having source references present (won't apply by default). After fixing that, dispatch is about 2X faster for me. So now in R-devel with that fix DataFrame is only about 6-7X slower that data.frame.

**Comment by hpages** [comment]
@lawremi 

Why not bump S4Vectors version?

I'm not sure how you could avoid dispatch here. Even if you manage to avoid dispatch on `NSBS()`, you would still need to dispatch on `extractROWS()` for every column.

Avoiding dispatch on `NSBS()` when `i` is already an NSBS object could probably be done by using something like `if (is(i , "NSBS"))` in the `NSBS()` generic before the call to `standardGeneric()` (which would turn `NSBS()` into a non-standard generic). But is it unreasonable to expect that S4 dispatch would be as efficient as an ugly bunch of `if (is(...))` statements, especially in the case of single dispatch?

**Comment by lawremi** [comment]
Sure, I'll go ahead and bump it. The `NSBS()` and `normalizeSingleBracketSubscript()` calls are taking a good bit of time, even beyond dispatch. We could have an "unsafe" variant of `extractROWS()` for this case. Of course, we'll still be dispatching on that; there's no way we can completely avoid dispatch.

**Comment by hpages** [comment]
Unlike the other `NSBS()` methods which actually normalize the user-supplied subscript, the `NSBS()` method for NSBS objects is a no-op that only checks that the normalized subscript is compatible with the object to subset `x`. This is a very simple check whose cost should be negligible. Unfortunately the method spends about 70% of its time in `NROW(x)` which is also time spent in dispatch.

The inefficiency of method dispatch is slowing down the entire S4Vectors/IRanges infrastructure, not just Dario's use case. An "unsafe" variant of `extractROWS()` would help Dario's use case only. I'm not convinced it's the right answer.

**Comment by lawremi** [comment]
Me neither. It was just a suggestion. A lot of the checking is not only redundant across columns but also with R's checks, in the basic vector case.

**Comment by hpages** [comment]
@lawremi Version bump please! We're getting close to the next release. [This change](https://github.com/Bioconductor/S4Vectors/commit/8a678b72d617fad319b976842be282208a0fc927) won't propagate if you don't bump the version. The earlier a change in a core package like S4Vectors can propagate the better. Thanks!

**Comment by DarioS** [comment]
But I thought a change to the methods package is what's required to fully solve the problem?

**Comment by lawremi** [comment]
There was a general problem in methods when source references were present. That's solved in R-devel. I just bumped the version. Crazy how there hasn't been any changes to S4Vectors in months, except for mine.

**Comment by DarioS** [comment]
It works fast if using R in-development.
