### ISSUE TITLE
cbind does not work on named list of DataFrames

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#3]
Hi Michael, @lawremi 

There seems to be a bug :bug: when binding a named `list` of `DataFrame`s with `cbind`. 

Take the following examples below where **Scenario 2** fails due to named elements:

**Scenario 1**. An unnamed `list` of `DataFrame`s
```
dfList0 <- list(DataFrame(A = 1:3, row.names = letters[24:26]),
    DataFrame(A = 4:6, row.names = letters[24:26]))
do.call(cbind, dfList0)
```

**Scenario 2**. A named list of `DataFrame`s
```
dfList1 <- list(assay1 = DataFrame(A = 1:3, row.names = letters[24:26]),
    assay2 = DataFrame(A = 4:6, row.names = letters[24:26]))
do.call(cbind, dfList1)
```

`Error in (function (x, ...)  : argument "x" is missing, with no default`

_Note_. FWIW, the same behavior is observed for a `SplitDataFrameList`

Thanks!

-Marcel

**Comment by lawremi** [comment]
This is actually an issue with calling `cbind()` with named arguments but not one named `x`. For example:

```
cbind(a = DataFrame(foo=1:10), b = DataFrame(bar=11:20))
```

Any, it's fixed, thanks for the report.
