### ISSUE TITLE
Pairs of parallel DataFrame objects

### ISSUE THREAD

**Issue by hpages** [Bioconductor/S4Vectors#33]
Hi Michael,

The TreeSummarizedExperiment package (https://github.com/Bioconductor/Contributions/issues/1058) seems to have a use case for a container holding a pair of DataFrame objects, a left DataFrame and a right DataFrame, with the 2 objects having the same number of rows. I was going to direct them to the Pairs container in S4Vectors but it doesn't seem to support that use case:
```
library(S4Vectors)
left <- DataFrame(left1=1:5, left2=letters[1:5])
right <- DataFrame(right1=sample(letters[1:3], 5, replace=TRUE),
                   right2=sample(c(TRUE, FALSE), 5, replace=TRUE),
                   right3=11:15)
Pairs(left, right)
# Error in Pairs(left, right) : length(first) == length(second) is not TRUE
```
Isn't that something that the Pairs container should support?

Thanks

**Comment by hpages** [comment]
Actually, after going a little bit deeper in the TreeSummarizedExperiment package, I came to the conclusion that they don't need that. So whether Pairs should support a pair of DataFrames or not is a philosophical question only ;-)

**Comment by lawremi** [comment]
Fairly easy to implement using the *ROWS stuff but there is a philosophical question around whether a row is something that can be paired. The column-oriented nature of the data frame leads us away from thinking of a row as an object. The same could be said though for the elements of atomic vectors.

**Comment by hpages** [comment]
Yes that's exactly what the ROWS stuff is about: to treat a DataFrame as a vector along its 1st dimension. We do this everywhere in the S4Vectors infrastructure, starting with the metadata columns (stored in a DataFrame that is _parallel_ to the object from a ROWS point of view). This was actually he motivation for introducing the ROWS stuff. This is also very useful for subsetting nested DataFrames where `extractROWS` can be called recursively on the columns without worrying about whether the column is an atomic vector, a matrix, a DataFrame, a GRanges object, etc...

So yes, rows can be paired. Like the ROWs of a GRanges object are implicitly paired with the ROWs of its metadata column DataFrame.

**Comment by lawremi** [comment]
Pushed it.

**Comment by hpages** [comment]
Thanks!
