### ISSUE TITLE
Add Factor class

### ISSUE THREAD

**Issue by hpages** [Bioconductor/S4Vectors#38]
A generalization of factor objects where the levels can be any vector-like object

As discussed here: https://github.com/Bioconductor/Contributions/issues/1114

**Comment by LTLA** [comment]
Should I PR in some code from _IndexedRelations_? Most of the underlying machinery is already there, along with the docs and tests.

**Comment by hpages** [comment]
Thanks for offering but it should not be necessary. Already started to work on this...

**Comment by hpages** [comment]
Done in S4Vectors 0.23.7. Please take a look and let me know how that works for you (report any problem in a new issue). Now will add GRangesFactor to GenomicRanges.

**Comment by LTLA** [comment]
Thanks Herve. The implementation matches up with what I was anticipating.

Looks like I'll archive IndexedRelations now. Alas! My thunder!
