### ISSUE TITLE
Factor constructor docs don't match up with code

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#41]
`?Factor` indicates that I should be able to do:

```r
F1 <- Factor(gr0, levels=gr1)
``` 

But the constructor fails upon trying this, with a `"'index' must be an integer vector"` message. Presumably there is a missing check inside `Factor()`, as below:

```r
    if (missing(index)) {
        index <- integer(0)
    } else if (is(index, class(levels))) { # ADDED
        index <- match(index, levels)      # ADDED
    } else {
        if (!is.numeric(index)) 
            stop(wmsg("'index' must be an integer vector"))
        if (!is.integer(index)) 
            index <- as.integer(index)
    }
```

`?Factor` also makes reference to `x=`, which presumably used to exist but no longer does.

**Comment by LTLA** [comment]
Woah - this is pretty surreal - now I get a different error after restarting my R session. Must have lost my own race condition between package installation and R start-up. Anyway:

```r
library(S4Vectors)
example(Factor)
## etc., etc.
## Factor> F1 <- Factor(gr0, levels=gr1)
## Error in (function (classes, fdef, mtable)  : 
##   unable to find an inherited method for function ‘FactorToClass’ for signature ‘"GRanges"’
```

**Comment by hpages** [comment]
There is a new union class in S4Vectors, `vector_OR_Vector`, but you need to re-install GenomicRanges in order for `GRanges` to be seen as a subclass of this new class.

Not sure exactly what's going on but it seems that each class definition carries its own copy of its ancestry tree and that ancestry tree is cached somewhere at installation time. Unfortunately that means that every package that defines a Vector offspring class will need to be re-installed before `vector_OR_Vector` is seen as an ancestor of that class.

**Comment by hpages** [comment]
Also make sure to use the latest S4Vectors (currently 0.23.8). Thanks!

**Comment by hpages** [comment]
I'll bump GenomicRanges version and will make it depend on S4Vectors>=  0.23.8. This will trigger propagation and reinstalltion of GenomicRanges on the user machines so at least people doing `example(Factor)` won't get the problem you got. Sorry for that.

**Comment by LTLA** [comment]
Yep, works fine now, thanks.
