### ISSUE TITLE
Factor validity method should use NROWS

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#42]
```r
library(S4Vectors)

df <- DataFrame(a=1:10, b=20)
Factor(index=1:10, df)
## Error in validObject(.Object) : invalid class “Factor” object: 
##    'index' slot contains out-of-bounds indices
```

This is because `length(x@levels)` in the validity method for `Factor` gives 2 for this DF. But for many `Factor` applications, I would say that the "length" of a DF is its `nrow` where each entry is a separate record of interest. This suggests that we should use `NROW(x@levels)` here instead.

The same issue is present in a few other functions, e.g., `.encode_as_Factor`, `.show_Factor` (on `x_levels`), `.have_same_levels`, `.concatenate_two_Factor_objects`.

**Comment by hpages** [comment]
Good catch, thanks! I've made some adjustments in S4Vectors 0.23.9 (commit a280558019e8c248b481192f9ac4de67ee8f6bbe) to accommodate Factor objects with data-frame-like levels.

**Comment by LTLA** [comment]
Aw yeah, works like a charm.
