### ISSUE TITLE
A nicer show method for Factors?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#43]
It would be nice to have a more informative `show` method for `Factor`s. For example:

```r
F1 <- Factor(gr0, levels=gr1) # from example(Factor)
show(F1)
```

... might give a preview:

```r
(GRanges)Factor object of length 8 and 1 metadata column
    seqnames    ranges strand |          ID
       <Rle> <IRanges>  <Rle> | <character>
  a     chrA      3-12      * |         ID1
  b     chrA      3-12      * |         ID2
  c     chrA      2-11      * |         ID3
  d     chrA      2-11      * |         ID4
  e     chrA      3-12      * |         ID5
  f     chrA      5-14      * |         ID6
  g     chrA      4-13      * |         ID7
  h     chrA      1-10      * |         ID8
  ---
Levels: GRanges object of length 6
```

... which would be more convenient than having to `unfactor(head(F1))` every time.

**Comment by hpages** [comment]
True. I was not sure how to display something informative in the general Factor case though so was thinking in doing this for GRangesFactor.

**Comment by LTLA** [comment]
Perhaps if we can detect it has `Vector` levels, we can use `showAsCell` and friends?

**Comment by hpages** [comment]
FWIW GRangesFactor objects (in GenomicRanges >= 1.37.11) have a nice `show()` method:
```
> library(GenomicRanges)
> GRangesFactor(levels=GRanges("chrA", IRanges(1:5, 10)), index=sample(5, 300, replace=TRUE))
GRangesFactor object of length 300 with 0 metadata columns:
        seqnames    ranges strand
           <Rle> <IRanges>  <Rle>
    [1]     chrA      5-10      *
    [2]     chrA      3-10      *
    [3]     chrA      1-10      *
    [4]     chrA      4-10      *
    [5]     chrA      4-10      *
    ...      ...       ...    ...
  [296]     chrA      2-10      *
  [297]     chrA      1-10      *
  [298]     chrA      2-10      *
  [299]     chrA      3-10      *
  [300]     chrA      1-10      *
5 levels:
  [1] chrA:1-10 chrA:2-10 chrA:3-10 chrA:4-10 chrA:5-10
```
Not sure this can be extended to Factor objects in general though. In particular it's not clear to me that using `showAsCell()` will be of any help when the levels are a data-frame-like object. Also not clear how we could displaying the "body" of the Factor nicely and in a consistent-looking way across all possible Factor objects.

**Comment by LTLA** [comment]
That's probably good enough for the time being. At some point, we may need to figure out how to `show` a `DataFrameFactor` object prettily, as this would be the other potential use case for `Factor`s.
