### ISSUE TITLE
bindROWS Wrong Documentation Page

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/S4Vectors#56]
Using `?bindROWS` shows the documentation of `LLint` but contains nothing about `bindROWS`.

**Comment by hpages** [comment]
Even though `bindROWS()` is exported it's not a user-facing function so it was not considered important to document it. It would be interesting to know how you came across `bindROWS` in the context of normal use of the software.

The only reason there is a documentation alias for `bindROWS` in the man page for `LLint` is to prevent `R CMD check` from complaining (there is a reason why this location was choosen). `bindROWS` is still a pretty recent addition to the S4Vectors infrastructure and, when I introduced it, I didn't want to advertise so I didn't document it. Maybe I'll move the alias to `?wmsg` where I already have a bunch of documentation aliases for other exported but non user-facing symbols. Or maybe it's time to document it in its own man page.

Assigning this to myself but won't be able to take care of it before the holidays.

H.

**Comment by DarioS** [comment]
Ah, it's intentional. A friend asked me why he should use `DataFrame` instead of `data.frame` so I used `showMethods` to find which ones are unique to `DataFrame`.

**Comment by hpages** [comment]
The 3 main reasons why the Bioconductor ecosystem prefers DataFrame over data.frame or tibble are:
1. The column of a DataFrame can be any vector-like object e.g. an IntegerList or CharacterList or DNAStringSet or Rle or GRanges or Hits object, etc..., and even another DataFrame object (i.e. DataFrame objects can be nested). You can't do this with a data.frame or tibble.
2. That's what we use to store the metadata columns of all Vector derivatives (e.g. the metadata columns of a GRanges or SummarizedExperiment object).
3. Transposing a DataFrame preserves the type of its columns (new in BioC 3.11). Whereas transposing a data.frame or tibble returns a matrix so the original column types are lost (unless they were all the same).

**Comment by hpages** [comment]
Some additional reasons:

  4. Better handling of rownames: they can be NULL or contain duplicates on a DataFrame.

  5. You can set metadata columns on a DataFrame itself.

**Comment by DarioS** [comment]
I used 5. all the time :)

**Comment by hpages** [comment]
I suppose it's ok to close this.
