### ISSUE TITLE
TransposedDataFrame conversion to *List behaviour inconsistent?

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/S4Vectors#71]
Hi,

The behavior of `TransposedDataFrame` during coercion for example to an `IntegerList` is a bit inconsistent.

```
>x <- DataFrame(1:4,5:8)
>as(x,"IntegerList")
IntegerList of length 2
[["X1.4"]] 1 2 3 4
[["X5.8"]] 5 6 7 8
>as(t(x),"IntegerList")
IntegerList of length 2
[["X1.4"]] 1 2 3 4
[["X5.8"]] 5 6 7 8
```

The result is the same, whether the data was transposed or not.

I know, that internally the data structure of a `TransposedDataFrame`stays the same and that mostly the accessors define the switched behaviour.

However, this example shows, that some things are a bit misleading. Are there any hints/advice for coercing to the desired result?

Thanks in advance.

Felix

**Comment by hpages** [comment]
Hi Felix,

This behaves as expected. What would be the desired result in your opinion?

H.

**Comment by FelixErnst** [comment]
Hi Herve,

my guess would have been, that the result will be transposed as well and look like this:

```
> as(t(x),"IntegerList")
IntegerList of length 4
[["1"]] 1 5
[["2"]] 2 6
[["3"]] 3 7
[["4"]] 4 8
```

For crude implementations `IntegerList(lapply(seq_len(ncol(tx)),function(i){unlist(tx[,i])}))` or `Reduce(pc,apply(tx,1L,function(z){as(z,"IntegerList")}))` work. In the later example, the internal names are not preserved.

This would carry over the transposed result. Is it reasonable to expect this?

For example `as.list(t(matrix(c(1:8),2))) != as.list(matrix(c(1:8),2))` and `as.list(t(data.frame(1:4,5:8))) != as.list(data.frame(1:4,5:8))` show that the result is carried over after transposing an object.

Felix

**Comment by hpages** [comment]
I don't think that would be reasonable. A TransposedDataFrame, like a DataFrame or data.frame, is still a _list_ of variables. Transposing didn't change the number of variables (a.k.a. the length of the list) and the variables are still the same so coercing to a list-like structure should produce you a list-like object with one list element per original variable:
```
library(S4Vectors)
library(IRanges)
DF <- DataFrame(aa=letters[1:4], bb=11:14)

## Transposing preserves the original variables:

length(DF)
# [1] 2
length(t(DF))
# [1] 2

names(DF)
# [1] "aa" "bb"
names(t(DF))
# [1] "aa" "bb"

as(t(DF), "CharacterList")
# CharacterList of length 2
# [["aa"]] a b c d
# [["bb"]] 11 12 13 14
```
You can achieve the behavior you are after with:
```
x <- DataFrame(1:4,5:8)

## **Effectively** transpose the data in the original DataFrame and return a new DataFrame
## containing the transposed data:
tx <- as(t(as.matrix(x)), "DataFrame")
tx
# DataFrame with 2 rows and 4 columns
#             V1        V2        V3        V4
#      <integer> <integer> <integer> <integer>
# X1.4         1         2         3         4
# X5.8         5         6         7         8

as(tx, "IntegerList")
# IntegerList of length 4
# [["V1"]] 1 5
# [["V2"]] 2 6
# [["V3"]] 3 7
# [["V4"]] 4 8
```

Hope this helps,
H.
