### ISSUE TITLE
Dependency on BiocGenerics >=  0.35.0 is not compatible with dependency R >= 3.3.0

### ISSUE THREAD

**Issue by renozao** [Bioconductor/S4Vectors#75]
The latest version available in 3.12 should depend on R >= 4.0.0 to match the requirement from BiocGenerics 0.36.

**Comment by hpages** [comment]
Requirement bumped in release (S4Vectors 0.28.1) and devel (S4Vectors 0.29.6). Thanks!

**Comment by renozao** [comment]
I think there is a whole chain of packages that would need such change, for
example IRanges also depends on R 3.1.0 although it depends on S4Vectors >=
0.27.12, which is only achievable with R >= 4.0.0.
Would the change be reflected in the release (3.12) repo or only in the
next release (3.13)?

**Comment by renozao** [comment]
From what I see this would be:

```
                  Package             Version 
XVector           "XVector"           "0.30.0"
VariantAnnotation "VariantAnnotation" "1.36.0"
InteractionSet    "InteractionSet"    "1.18.0"
genoset           "genoset"           "1.45.1"
GenomicRanges     "GenomicRanges"     "1.42.0"
Cardinal          "Cardinal"          "2.8.0" 
```

**Comment by FelixErnst** [comment]
@renozao Thanks for the info. 
@hpages Depending on what you decide to do, I can take care of the changes in RNAmodR and Structstrings

**Comment by hpages** [comment]
@FelixErnst Sure, please go ahead. Thanks!

@renozao I'll take care of a few other packages that I have control of. Thanks!

**Comment by renozao** [comment]
Great thanks.
