### ISSUE TITLE
apply on DataFrame does not subset containing CharacterList

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#78]
Hi Michael, @lawremi 

When I want to iterate down the rows of a `DataFrame` using apply,
I don't get the expected element of the `CharacterList` in the `DataFrame`

This probably has to do with the fact that I'm using `base::apply`:

```r
library(S4Vectors)
library(IRanges)
test <- DataFrame(A = 1:2, B = CharacterList(c("a", "b"), "c"))
## expecting a single element of the CharacterList
apply(test, 1L, I)

## such as
test[1, ]
test[2, ]
```

cc: Hervé @hpages

**Comment by lawremi** [comment]
Added the S3 `cbind.List()` to handle the case when some columns are list and some not during conversion to matrix.  There could also be an `rbind.List()` but not sure if there's a great use case.

**Comment by LiNk-NY** [comment]
Thanks Michael for the quick fix. 
I took the liberty to update the order of the method definition and
helper function because I couldn't install the package. 
6ee757d80cf0ae1e88cbb91ee695ee5770985181

**Comment by lawremi** [comment]
Great, thanks for the catch.
