### ISSUE TITLE
Performance degradation when assigning to a `Vector`-containing list 

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#86]
Consider this minimal example on the current devel:

```r
library(S4Vectors)
setClass("FOO", contains="Vector", slots=c(A="integer"))
setMethod("updateObject", "FOO", function(object, ...) {
    Sys.sleep(10)
    object
})

el <- List(new("FOO"), new("FOO"))
el[[1]] <- el[[1]] # hits the updateObject's sleep
````

The real use case is that **MultiAssayExperiment** uses an `ExperimentList`, and reassigning into that triggers an `updateObject()` on the list elements... which includes some large SEs containing `HDF5Array`s. This results in a several-second delay when the assignment is performed for each of multiple SEs.

I would not have expected a simple assignment like this to fire the `updateObject()` methods of the list elements. Some digging suggests that this is because the `SimpleList`'s `updateObject()` will call the `updateObject()` methods of its `Vector` elements. Perhaps this should be disabled in the context of `[[<-` and other simple getter/setter operations.

**Comment by LiNk-NY** [comment]
This should have some effect in speeding it up...
https://github.com/Bioconductor/S4Vectors/pull/87

**Comment by hpages** [comment]
I applied Marcel's PR. See #87 for comments.
