### ISSUE TITLE
subset(x) should work (and be a no-op) on zero-length Vector derivatives

### ISSUE THREAD

**Issue by hpages** [Bioconductor/S4Vectors#89]
Hi @lawremi ,

Related to https://github.com/Bioconductor/SummarizedExperiment/issues/58

We get a similar error with a zero-row DataFrame object:
```
library(S4Vectors)
DF <- DataFrame(aa=11:14, bb=21:24)

subset(DF)
# DataFrame with 4 rows and 2 columns
#          aa        bb
#   <integer> <integer>
# 1        11        21
# 2        12        22
# 3        13        23
# 4        14        24

subset(DF[0, ])
# Error: subscript is a logical vector with out-of-bounds TRUE values
```
or with a zero-length GRanges object:
```
library(GenomicRanges)
gr <- GRanges("chr1", IRanges(1:4, 10))

subset(gr)
# GRanges object with 4 ranges and 0 metadata columns:
#       seqnames    ranges strand
#          <Rle> <IRanges>  <Rle>
#   [1]     chr1      1-10      *
#   [2]     chr1      2-10      *
#   [3]     chr1      3-10      *
#   [4]     chr1      4-10      *
#   -------
#   seqinfo: 1 sequence from an unspecified genome; no seqlengths

subset(gr[0])
# Error: subscript is a logical vector with out-of-bounds TRUE values
```

The various `subset()` methods implemented in **S4Vectors** and **SummarizedExperiment** rely on `S4Vectors:::evalqForSubset()` to turn the user-supplied `subset` expression into a logical vector that is then used to subset `x`. However, the current implementation of `S4Vectors:::evalqForSubset()` returns a single `TRUE` when no `subset` expression is supplied:
```
> S4Vectors:::evalqForSubset
function (expr, envir, ...) 
{
    if (missingArg(substitute(expr), parent.frame())) {
        TRUE             <-- single TRUE!
    }
    else {
        i <- evalArg(substitute(expr), envir, ..., where = parent.frame())
        normSubsetIndex(i)
    }
}
<bytecode: 0x55ba9580ffe0>
<environment: namespace:S4Vectors>
```
which causes the error downstream when this single TRUE is used to subset a zero-length object.

Interestingly it looks like `S4Vectors:::evalqForSelect()` (also used in various `subset()` methods) is doing the right thing:
```
> S4Vectors:::evalqForSelect
function (expr, df, ...) 
{
    if (missingArg(substitute(expr), parent.frame())) {
        rep(TRUE, ncol(df))   <--- good!
    }
    else {
        nl <- as.list(seq_len(ncol(df)))
        names(nl) <- colnames(df)
        evalArg(substitute(expr), nl, ..., where = parent.frame())
    }
}
<bytecode: 0x55ba95f51318>
<environment: namespace:S4Vectors>
```
so maybe `S4Vectors:::evalqForSubset()` could be modified in a similar manner e.g. by using something like `rep(TRUE, NROW(envir))`?

Thanks,
H.

**Comment by danielinteractive** [comment]
Thanks @lawremi for looking into this, let us know if any questions on the application of this :-)

**Comment by kpagacz** [comment]
Would you mind if I submitted a PR for this?

**Comment by hpages** [comment]
Hopefully @lawremi can chime in. `S4Vectors:::evalqForSubset` and `S4Vectors:::evalqForSelect` are his babies, which he implemented in order to be able to support `subset()` on Vector derivatives.

Michael?

**Comment by hpages** [comment]
It should be taken care of @kpagacz @danielinteractive.

**Comment by kpagacz** [comment]
thanks a lot
