### ISSUE TITLE
3 arguments passed to .Internal(is.unsorted) which requires 2

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/S4Vectors#95]
I am getting this error, using R 4.2.0 and Bioconductor 3.15:

```
library(scRNAseq)
> sce <- HermannSpermatogenesisData()
[...]
Error in ..Internal(is.unsorted(x, FALSE, FALSE)) : 
  3 arguments passed to .Internal(is.unsorted) which requires 2
```

I've chased the issue down to this line (and the next)
https://github.com/Bioconductor/S4Vectors/blob/338534bfb5fb6ada3f2abc144017bc8ce0aab6c3/R/isSorted.R#L149

That's as far as I managed to go. Thoughts?

**Comment by mtmorgan** [comment]
The S4Vectors code checks to see if your R version is 4.2.0 or greater to accommodate a change to `is.unsorted` that was made on Sept 28 https://github.com/wch/r-source/commit/e749e78ec0e66365297e12e7e6726de85355d99e  It seems the version bump to 4.2.0 was on Apr 19 https://github.com/wch/r-source/commit/c457f9a5f732ec935e92975cc9492961c023e975 so S4Vectors would be wrong for any R-devel from Apr 19 to Sept 28.

FWIW I have
```
> R.version.string
[1] "R Under development (unstable) (2021-10-28 r81109)"
```

**Comment by kevinrue** [comment]
Yup. Updating my R-devel solved it. Thanks!

**Comment by zope410** [comment]
Thank you guys, I had a similar issue with the fPortfolio package. Regards, Carlos
