### ISSUE TITLE
isEmpty does not return a single logical with list

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#98]
Hi Hervé, @hpages 
I was trying this on a `data.frame` and found that the last line in the `ANY` method:
https://github.com/Bioconductor/S4Vectors/blob/1421c0d4415237876fde1aae7f47d247c5049cb0/R/List-class.R#L53-L65
should be something like: 

```r
all(vapply(x, function(xx) isEmpty(xx), logical(1L)))
```

Here is a reproducible example:

```
> list(a = character(0L), b = logical(0L))
$a
character(0)

$b
logical(0)

> test <- list(a = character(0L), b = logical(0L))
> isEmpty(test)
   a    b 
TRUE TRUE 
```

**Comment by hpages** [comment]
Great! I had no idea that people were using this =:-O

Fixed: a58ee53cda1b03bcc0167945113a7e623077ac85

H.
